*****************************************************************************************************************
*   FILENAME    *    PRIORITY    *  TEST-CASE LENGTH  *  NUMBER OF ACTIONS  *    BUG PRODUCED  *  EXCEPTION
*****************************************************************************************************************
* Readme  *      HIGH      *         4         *       0         *       True     *  test-case failed to execute with following message: b'  File "Readme", line 1\r\n    This empty-file is needed to run AGTGAdriver.press_keycode(3) \r\n             ^\r\nSyntaxError: invalid syntax\r\n'
_________________________________________________________________________________________________________________
* TestCase00.py  *      HIGH      *         22         *       4         *       True     *  test-case failed to execute with following message: b'Traceback (most recent call last):\r\n  File "TestCase00.py", line 8, in <module>\r\n    driver = webdriver.Remote(command_executor=port, desired_capabilities={\'automationName\' : \'UiAutomator2\',\'deviceName\': \'Moto G (5)\',\'platformName\': \'Android\',  \'app\': \'C:/Users/ze0396/Desktop/AGTGA/APKS/LifeHack.apk\' , \'autoGrantPermissions\' : \'true\', \'appWaitActivity\' : \'*.*\',\'fullreset\' : \'false\',\'noReset\' : \'true\' } ) \r\n  File "C:\\Users\\ze0396\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\appium\\webdriver\\webdriver.py", line 151, in __init__\r\n    proxy\r\n  File "C:\\Users\\ze0396\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py", line 157, in __init__\r\n    self.start_session(capabilities, browser_profile)\r\n  File "C:\\Users\\ze0396\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\appium\\webdriver\\webdriver.py", line 227, in start_session\r\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\r\n  File "C:\\Users\\ze0396\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py", line 321, in execute\r\n    self.error_handler.check_response(response)\r\n  File "C:\\Users\\ze0396\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py", line 242, in check_response\r\n    raise exception_class(message, screen, stacktrace)\r\nselenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: The instrumentation process cannot be initialized. Make sure the application under test does not crash and investigate the logcat output.\r\n\r\n'
_________________________________________________________________________________________________________________
* TestCase01.py  *       LOW      *         19         *       3         *       False     *  Server-side error occurred. Please rerun this test-case
_________________________________________________________________________________________________________________
* TestCase02.py  *       LOW      *         22         *       4         *       False     *  Server-side error occurred. Please rerun this test-case
_________________________________________________________________________________________________________________
* TestCase03.py  *       LOW      *         22         *       4         *       False     *  Server-side error occurred. Please rerun this test-case
_________________________________________________________________________________________________________________
* TestCase04.py  *       LOW      *         22         *       4         *       False     *  Server-side error occurred. Please rerun this test-case
_________________________________________________________________________________________________________________
* TestCase05.py  *       LOW      *         25         *       5         *       False     *  Server-side error occurred. Please rerun this test-case
_________________________________________________________________________________________________________________
* TestCase06.py  *       LOW      *         19         *       3         *       False     *  Server-side error occurred. Please rerun this test-case
_________________________________________________________________________________________________________________
* TestCase07.py  *       LOW      *         19         *       3         *       False     *  Server-side error occurred. Please rerun this test-case
_________________________________________________________________________________________________________________
* TestCase08.py  *       LOW      *         31         *       7         *       False     *  Server-side error occurred. Please rerun this test-case
_________________________________________________________________________________________________________________
* TestCase09.py  *       LOW      *         25         *       5         *       False     *  Server-side error occurred. Please rerun this test-case
_________________________________________________________________________________________________________________
* TestCase10.py  *       LOW      *         22         *       4         *       False     *  Server-side error occurred. Please rerun this test-case
_________________________________________________________________________________________________________________
* TestCase11.py  *       LOW      *         16         *       2         *       False     *  Server-side error occurred. Please rerun this test-case
_________________________________________________________________________________________________________________
* TestCase12.py  *       LOW      *         25         *       5         *       False     *  Server-side error occurred. Please rerun this test-case
_________________________________________________________________________________________________________________
* TestCase13.py  *       LOW      *         22         *       4         *       False     *  Server-side error occurred. Please rerun this test-case
_________________________________________________________________________________________________________________
* TestCase14.py  *       LOW      *         28         *       6         *       False     *  Server-side error occurred. Please rerun this test-case
_________________________________________________________________________________________________________________
* TestCase15.py  *       LOW      *         19         *       3         *       False     *  Server-side error occurred. Please rerun this test-case
_________________________________________________________________________________________________________________
* TestCase16.py  *       LOW      *         22         *       4         *       False     *  Server-side error occurred. Please rerun this test-case
_________________________________________________________________________________________________________________
* TestCase17.py  *       LOW      *         16         *       2         *       False     *  Server-side error occurred. Please rerun this test-case
_________________________________________________________________________________________________________________
* TestCase18.py  *       LOW      *         28         *       6         *       False     *  Server-side error occurred. Please rerun this test-case
_________________________________________________________________________________________________________________
* TestCase19.py  *       LOW      *         19         *       3         *       False     *  Server-side error occurred. Please rerun this test-case
_________________________________________________________________________________________________________________
* TestCase20.py  *       LOW      *         25         *       5         *       False     *  Server-side error occurred. Please rerun this test-case
_________________________________________________________________________________________________________________
*   Average Test-Case Length               =                         22.94736842105263
*   Average Action per Test-case           =                         4.315789473684211
*****************************************************************************************************************

Process finished with exit code 0
